#  Licensed to Muhammad Hamadto
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#     http://www.apache.org/licenses/LICENSE-2.0
#
#   See the NOTICE file distributed with this work for additional information regarding copyright ownership.
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

name: Publish package to Maven Central

on:
  release:
    types: [published]

env:
  SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
  SONATYPE_TOKEN: ${{ secrets.SONATYPE_TOKEN }}
  GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
  GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Configure Maven settings for Sonatype Central Portal
        run: |
          mkdir -p $HOME/.m2
          cat > $HOME/.m2/settings.xml <<EOF
          <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
                    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                    xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
                                        https://maven.apache.org/xsd/settings-1.0.0.xsd">
            <servers>
              <server>
                <id>central</id>
                <username>\${env.SONATYPE_USERNAME}</username>
                <password>\${env.SONATYPE_TOKEN}</password>
              </server>
            </servers>
          </settings>
          EOF

      - name: Setup GPG
        run: |
          # Create GPG directory
          mkdir -p ~/.gnupg
          chmod 700 ~/.gnupg
          
          # Configure GPG
          echo "allow-loopback-pinentry" >> ~/.gnupg/gpg-agent.conf
          echo "pinentry-mode loopback" >> ~/.gnupg/gpg.conf
          echo "use-agent" >> ~/.gnupg/gpg.conf
          echo "batch" >> ~/.gnupg/gpg.conf
          
          # Kill any existing gpg-agent
          gpgconf --kill gpg-agent

      - name: Import GPG key
        run: |
          echo "$GPG_PRIVATE_KEY" | gpg --batch --yes --import
          
          # List keys to verify import
          gpg --list-secret-keys --keyid-format LONG
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}

      - name: Deploy to Maven Central
        run: |
          mvn clean deploy -Prelease \
            --batch-mode \
            --no-transfer-progress \
            -Dgpg.passphrase="${GPG_PASSPHRASE}"
        env:
          MAVEN_USERNAME: ${{ env.SONATYPE_USERNAME }}
          MAVEN_PASSWORD: ${{ env.SONATYPE_TOKEN }}
          GPG_PASSPHRASE: ${{ env.GPG_PASSPHRASE }}